spring.application.name=API-Gateway
server.port=8765
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
management.endpoints.web.exposure.include=*
#spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.server.webflux.routes[0].id=employeeservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://EMPLOYEESERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employees/**

spring.cloud.gateway.server.webflux.routes[1].id=leaveservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://LEAVESERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/leave-requests/**